[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
<<<<<<< HEAD
  
=======
>>>>>>> d60512a (Updated EduTrack)

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
